name: test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
env:
  GO111MODULE: "on"
  GO_LATEST_VERSION: "1.16.x"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # with Ubuntu 18.04, python-gnomekeyring has been deprecated and deleted
        # from the archives so we need to use ubuntu-16.04.
        # Do not forget to update Install Dependencies (Linux) step if the version
        # of ubuntu is changed.
        # https://launchpad.net/ubuntu/+source/gnome-python-desktop/+publishinghistory
        os: [ ubuntu-16.04, macos-latest ]
        go-version: [ 1.16.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y python-gnomekeyring gnome-keyring
          dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
        if: matrix.os == 'ubuntu-16.04'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-cache

      - name: Test
        id: test
        run: |
          make test

      - name: Upload code coverage (unit)
        if: matrix.go-version == env.GO_LATEST_VERSION
        uses: codecov/codecov-action@v1
        with:
          file: ./unit.coverprofile
          flags: unittests-${{ runner.os }}

      - name: Upload code coverage (features)
        if: matrix.go-version == env.GO_LATEST_VERSION
        uses: codecov/codecov-action@v1
        with:
          file: ./features.coverprofile
          flags: featurestests-${{ runner.os }}
